#import "NSObject+URL.h"
#import "EtcHostsURLProtocol.h"

@implementation NSObject (URL)

+ (void)load
{
    [NSURLProtocol registerClass:[EtcHostsURLProtocol class]];
    [EtcHostsURLProtocol configureHostsWithBlock:^(id <EtcHostsConfiguration> configuration) {
        NSArray *blockedHosts = @[
            // @"graph.facebook.com",
            // @"ff.garena.com",
            // @"appsflyersdk.com",
            // @"ff.dr.grtc.garenanow.com",
            // @"1e100.net",
            // @"gopapi.io",
            // @"appsflyer.com",
            // @"hocal.com",
            // @"listdl.com",
            // @"dl.listdl.com",
            // @"garena.com",
            // @"freefiremobile.com",
            // @"akamaiedge.net",
            // @"garenanow.com",
            // @"akamaihd.net",
            @"www.facebook.com",
            @"blog.garena.com",
            @"support.garena.vn",
            @"forum.garena.vn",
            @"hotro.garena.vn",
            @"report.ff.garena.com",
            @"dav.orange.fr",
            @"msg.t-mobile.com",
            @"www.whatismyip.com",
            @"ipinfo.io",
            @"www.iplocation.net",
            @"www.whatismyipaddress.com",
            @"www.checkip.com",
            @"www.myip.com",

            @"dl.dir.freefiremobile.com",
            @"csoversea.stronghold.freefiremobile.com",
            @"vn.event.freefiremobile.com",
            @"ff.sdk.grtc.garenanow.com",
            @"dl.listdl.com",
            @"gin.freefiremobile.com",
            @"dl.gmc.freefiremobile.com",
            @"firebase-settings.crashlytics.com",
            @"dl.cdn.freefiremobile.com",
            @"dl.aw.freefiremobile.com",
            @"dl.castle.freefiremobile.com",
            @"bc.googleusercontent.com",
            @"230.170.87.34.bc.googleusercontent.com",
            @"230.170.87.35.bc.googleusercontent.com",
            @"57.183.185.34.bc.googleusercontent.com",
            @"57.183.185.35.bc.googleusercontent.com",
            @"14.177.87.35.bc.googleusercontent.com",
            @"14.177.87.34.bc.googleusercontent.com",
            @"45.76.126.34.bc.googleusercontent.com",
            @"45.76.126.35.bc.googleusercontent.com",
            @"in-f.globh.com",
            @"hackstorenew.bd.freefiremobile.com",
            @"csoversea.castle.freefiremobile.com",
            @"common.freefiremobile.com",
            @"version.common.freefiremobile.com",
            @"client.common.freefiremobile.com",
            @"dl.ctl.freefiremobile.com",
            @"dl.ctlin.freefiremobile.com",
            @"dl.cvs.freefiremobile.com",
            @"ind.event.freefiremobile.com",
            @"za.event.freefiremobile.com",
            @"bd.event.freefiremobile.com",
            @"sac.event.freefiremobile.com",
            @"fg.freefiremobile.com",
            @"dl.gcp.freefiremobile.com",
            @"dl.hw.freefiremobile.com",
            @"client.ind.freefiremobile.com",
            @"rampage3.ind.freefiremobile.com",
            @"dl.ks.freefiremobile.com",
            @"m.freefiremobile.com",
            @"test.maxcb.freefiremobile.com",
            @"za.network.freefiremobile.com",
            @"vn.network.freefiremobile.com",
            @"id.network.freefiremobile.com",
            @"bd.network.freefiremobile.com",
            @"mystery6shop.sea.freefiremobile.com",
            @"mystery7shop.sea.freefiremobile.com",
            @"mysteryshop.sea.freefiremobile.com",
            @"mystery8shop.sea.freefiremobile.com",
            @"mystery5shop.sea.freefiremobile.com",
            @"rampage2.sea.freefiremobile.com",
            @"testsummer.sea.freefiremobile.com",
            @"instructions.us.freefiremobile.com",
            @"client.us.freefiremobile.com",
            @"ffcc.us.freefiremobile.com",
            @"guide.us.freefiremobile.com",
            @"hackstorenew.us.freefiremobile.com",
            @"dev.winterlands.freefiremobile.com",
            @"dl.wsu.freefiremobile.com",
            @"www.freefiremobile.com",
            @"ck.getcookiestxt.com",
            @"eu1.clevertap-prod.com",
            @"wizhumpgyros.com",
            @"coccyxwickimp.com",
            @"webmail-who-int.000webhostapp.com",
            @"010sec.com",
            @"01mspmd5yalky8.com",
            @"0byv9mgbn0.com",
            @"ns6.0pendns.org",
            @"dns.0pengl.com",
            @"12724.xyz",
            @"21736.xyz",
            @"www.analytics.247sports.com",
            @"2no.co",
            @"www.2no.co",
            @"logitechlogitechglobal.112.2o7.net",
            @"www.logitechlogitechglobal.112.2o7.net",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",
            // @"",



        ];

        for (NSString *host in blockedHosts) {
            [configuration resolveHostName:host toIPAddress:@"127.0.0.1"];
        }
    }];
}

@end